# Generated by Django 4.2.4 on 2023-08-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False, verbose_name='URL-адрес изображения')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='Количество просмотров')),
                ('categories', models.ManyToManyField(null=True, related_name='proxies', to='proxy.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
            },
        ),
    ]
